server:
  port: 9085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/microserviceEcommerceAuthDb
  jpa:
    hibernate:
      ddl-auto: update